version: '3'
services:
    zoo1:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
        volumes:
            - ./zoo/1:/data
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        ports:
            - 2182:2181
        volumes:
            - ./zoo/2:/data
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper
        restart: always
        ports:
            - 2183:2181
        volumes:
          - ./zoo/3:/data
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    kafka1:
        image: r1ckr/kafka:0.1
        restart: always
        volumes:
          - ./kafka/1:/data
        environment:
          ZK: zoo1:2181,zoo2:2181,zoo3:2181
          KAFKA_BROKER_ID: 0
        depends_on:
          - zoo1
          - zoo2
          - zoo3

    kafka2:
        image: r1ckr/kafka:0.1
        restart: always
        volumes:
          - ./kafka/2:/data
        environment:
          ZK: zoo1:2181,zoo2:2181,zoo3:2181
          KAFKA_BROKER_ID: 1
        depends_on:
          - zoo1
          - zoo2
          - zoo3

    kafka3:
        image: r1ckr/kafka:0.1
        restart: always
        volumes:
          - ./kafka/3:/data
        environment:
          ZK: zoo1:2181,zoo2:2181,zoo3:2181
          KAFKA_BROKER_ID: 2
        depends_on:
          - zoo1
          - zoo2
          - zoo3